---
- hosts: all
  become: yes
  tasks:
    - name: install latest version of all
      yum:
        name: '*'
        state: latest
    - name: reiniciar equipo
      shell: sleep 3 && reboot
      
      async: 1
      poll: 0
      
    - name: esperar por reconexion
      wait_for_connection:
        connect_timeout: 60
        sleep: 5
        delay: 5
        timeout: 120
...
