---
- hosts: node01
  remote_user: root
  become: yes
  tasks:
    - name: disabling firewalld
      systemd:
	    name: firewalld
	    state: stopped
		enabled: no
    - name: disabling and editing selinux config
	  lineinfile:
	    path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
	  shell: setenforce 0
    - name: install needed packages for gitlab
	  yum:
	   name:
       - curl
       - policycoreutils-python
       - openssh-server
       - postfix
       state: latest
    - name: setting up postfix service
      systemd:
        name: postfix
        state: started
        enabled: yes
    - name: getting ready gitlab repos
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
      args:
        executable: /usr/bin/bash
        chdir: /backup
    - name: installing Gitlab packages from new repo list
      yum:
        name: gitlab-ce
        state: present
    - name: editing config file from Gitlab
      lineinfile:
        regexp: '^external_url'
        line: ' external_url "http://gitlab.itzgeek.local" '
    - name: reconfiguring Gitlab service
      shell: gitlab-ctl reconfigure
...
