---
- hosts: all
  become: yes
  tasks:
    - name: check if apache http service is installed or latest
      yum:
        name: nginx
        state: latest
    - name: ensure http service is running
      service:
        name: nginx
        state: started
        enabled: yes
...
