---
- hosts: node01
  remote_user: root
  become: yes
  tasks:
    - name: check if apache http service is installed or latest
      yum:
        name: httpd
        state: latest
    - name: ensure http service is running
      service:
        name: httpd
        state: started
    - name: enable http service on boot
      systemd:
        name: httpd
        enabled: yes
...
