---
- hosts: node01
  become: yes
  tasks:
    - name: see if net-snmp package is installed
      yum:
        name: net-snmp
        state: latest
    - name: editing some lines
      shell: sed -i 's/^com2/#com2/g /etc/snmp/snmpd.conf'
    - name: restarting service
      service:
        name: snmpd
        state: restarted
...
